- README.md
There are Some Operating Systems that separate the PostgreSQL client libraries from the server libraries.
> Add note about Postgres client libraries

- Cargo.lock
- Cargo.toml
- migrations/2018-01-08-072612_status_uri/down.sql
- migrations/2018-01-08-072612_status_uri/up.sql
- src/db/models.rs
- src/main.rs
* Adds the `created_at` column to the struct as it is already in the schema
* Adds `get_uri` in a similar style to `Account`'s; adds `account` as a convenience function that I'm sure we'll need a few more times at least
The style of `Status::get_uri` was selectively fixed up by rustfmt-nightly (I didn't apply style fixes outside my own changes). It has some very different opinions than what is currently present in the code base.
> Start implementation of db::models::Status

- README.md
When I ran through the install instructions (on Arch Linux), running `cargo install diesel_cli` required not just libpqsql but also libmysqlclient.
In the interests of assuming as little of the reader as possible, I am updating the docs to make this requirement explicit.
> Documentation: Diesel CLI requires libmysqlclient

- README.md
Those unfamiliar with Rust's `cargo` installation tool for libraries
and tools may not be aware that any binaries it installs will be
installed in `~/.cargo/bin`.
Making that explicit in the documentation.
> README: Make clear the assumption that ~/.cargo/bin is in your PATH

- Cargo.lock
- Cargo.toml
- src/db/models.rs
- src/error.rs
- src/main.rs
- src/routes/ap.rs
- src/routes/ui.rs
> Improve error handling and use Failure

- .travis.yml
- appspec.yml
- scripts/deploy.sh
- scripts/initd_rustodon
- scripts/staging_start.sh
- scripts/staging_stop.sh
I have created a Continuous Deployment server over at http://rustodon.glitchsocial. (Note it's http only right now, easy to make it SSL but figure I'll wait until we have uptake)
This merge configures travis.yml to invoke AWS CodeDeploy to push out the latest successful master build of Rustodon over to it, and run migrations. You can see the scripts that run for deployment, they have been added.
(The deployment server is a lightly configured at the moment, but I don't think I will require any more modifications to the codebase to make the deployment process more robust.)
> Enable AWS CodeDeploy to our project's CD server

- Cargo.lock
- Cargo.toml
- src/main.rs
- src/routes/ui.rs
- src/templates/mod.rs
`derive_builder` is _extremely_ nice, but not flexible enough (at the moment) to specify the difference between an `String` field that is optional and settable with a string (`.field(value: Into<String>)`), and an `String` field that is optional and settable with an `Option<String>` (`.field(value: Option<Into<String>>)`).
By getting rid of `derive_builder`, I was also able to put all the Builder behavior directly on `Page`, which actually ends up being much more ergonomic. I also made page content optional, to avoid having to build and validate Builder chains, like with `derive_builder`.
Before:
```rust
let page = PageBuilder::default()
.title("foo")
.content(html! { p "foo" })
.build()
.unwrap();
```
This PR:
```rust
let page = Page::new()
.title("foo")
.content(html! { p "foo" });
```
> Remove derive_builder

- Cargo.lock
rustc 1.27.0 introduced changes that breaks pear_codegen < 0.0.14 and
rocket_codegen < 0.3.7.  To update those crates, it was also necessary
to update to rocket 0.3.7.
> deps: update rocket_codegen and pear_codegen

- README.md
Fix installation method on Debian.
[Reference](https://www.linuxquestions.org/questions/linux-newbie-8/apt-get-install-mysql-server-mysql-clinet-libmysqlclient-dev-4175607306/)
> fix installation method on Debian

- README.md
- docker-compose.yml
This PR adds a `docker-compose.yml` which allows to provision a database in a straightforward and convenient way using `docker-compose`.
I've also taken the liberty of updating the documentation.
> Added docker-compose configuration for convenient database setup

- README.md
According to the [diesel_cli README installation instructions](https://github.com/diesel-rs/diesel/tree/master/diesel_cli#installation) you can avoid having to install both, the development libraries for MySQL as well as SQLite, if you only enable the `postgres` feature.
This not only simplifies the installation process but also leaves a smaller footprint.
> Adjust README instructions for diesel_cli

- src/routes/ui/mod.rs
- style/_profile.scss
Closes #50.
Link users to their profile instead of the edit form; link the edit form on their profile page.
> Profile edit link refactor

- .gitignore
- scripts/setup
This PR fixes #27.
Following the advice mentioned in #27, this PR uses the `scripts/setup` bootstrap to create a `Rocket.toml` file that will allow for a persistent secret across server restarts. It also prevents that file from being added to source control.
> Generate Rocket.toml at setup time

- .gitignore
- scripts/setup
Some Ruby setups will take a `bundle install` and attempt to instally globally, requiring `sudo` permissions. This PR changes it such that `bundle install` happens inside the project, requiring only local perms. cc @yipdw
> Bundle install into vendor rather than potentially in system gems

- src/routes/well_known.rs
Some webfinger clients - Pleroma, for example - query webfinger with a
resource that looks like `user@domain` instead of `acct:user@domain`.
This commit fixes an unwrap panic that was occuring due to our naive
handling of the acct: prefix.
> webfinger: fix requests without acct: prefix on resource

- Cargo.lock
- Cargo.toml
- lib/posticle/Cargo.toml
- lib/posticle/src/lib.rs
- lib/posticle/src/tokens.rs
- lib/resopt/Cargo.toml
- lib/resopt/src/lib.rs
- src/activitypub/mod.rs
- src/error.rs
- src/main.rs
- src/routes/ap.rs
- src/routes/ui/auth.rs
- src/routes/ui/mod.rs
- src/routes/ui/templates.rs
- src/routes/ui/view_helpers.rs
- src/routes/well_known.rs
- src/transform.rs
Fixes #139.
The compiler also said that the `custom_derive` feature was removed and subsumed by `#[proc_macro_derive]`, but it compiled fine without the attribute. Do I leave it out or should I place it somewhere?
> Update to Rust 2018 edition

- src/activitypub/mod.rs
- src/db/idgen.rs
- src/db/models/account.rs
- src/db/models/status.rs
- elide some explicit lifetimes
- stop clippy from linting `IdGenerator::next()` method as something that should `impl Iterator` for best ergonomics (it shouldn't)
- log an error if the `ActivityStreams` guard fails to serialize
> Clippy cleanup

- src/activitypub/mod.rs
- src/db/mod.rs
- src/db/models/account.rs
- src/db/models/status.rs
- src/db/models/user.rs
- src/routes/ui/view_helpers.rs
there is no point in passing the guard around because we have to then do the silly `&*` deref trick when using it! everything should just take `&PgConnection` (here, type-aliased to `&db::DbConnection`). autoderefs will occur so we don't need to change any code other than switching from `Connection` to `DbConnection` and dropping the deref hacks. this also makes testing individual subsystems easier :)
also, this brings our total of deref hacks down to one:
```
λ ~/git/rustodon  
» ag -Q '&*'
src/routes/ui/mod.rs
132:    diesel::delete(&status).execute(&*db_conn)?;
```
> db: nothing but routes should take the db::Connection guard as an arg

- Cargo.toml
Dependabot failed after structopt 0.2.17 got yanked from Crates.io.
> structopt 0.2.17 → 0.2.16

- src/routes/well_known.rs
This allow using Firefox or any browser to retreive node information.
With this format specifier, Rocket will route FF request to `/<username>/<status_id>`
because FF add the `Accept: text/html` in it's request headers.
Closes #272.
> Remove the format specifier for /nodeinfo/2.0 route (#272)

- scripts/default_rustodon
- scripts/rustodon.service
In service file, assume Rustodon instance is deployed in /srv/rustodon.
Include an /etc/default/rustodon environment file to define required Rocket env.
Variables in `/srv/rustodon/.env` may be moved in `/etc/default/rustodon`.
See full commit message for usage.
This is my systemd service file I use in may VPS.
Regards,
David
> Add systemd service for rustodon (#135)
